const FETCH_HOUSES_REQUESTED = "mobilereality/HOUSES/FETCH_HOUSES_REQUESTED";
const FETCH_HOUSES_FULFILLED = "mobilereality/HOUSES/FETCH_HOUSES_FULFILLED";
const FETCH_HOUSES_REJECTED = "mobilereality/HOUSES/FETCH_HOUSES_REJECTED";
const FETCH_HOUSE_BY_ID_REQUESTED =
  "mobilereality/HOUSES/FETCH_HOUSE_BY_ID_REQUESTED";
const FETCH_HOUSE_BY_ID_FULFILLED =
  "mobilereality/HOUSES/FETCH_HOUSE_BY_ID_FULFILLED";
const FETCH_HOUSE_BY_ID_REJECTED =
  "mobilereality/HOUSES/FETCH_HOUSE_BY_ID_REJECTED";
const DELETE_HOUSE_BY_ID_REQUESTED =
  "mobilereality/HOUSES/DELETE_HOUSE_BY_ID_REQUESTED";
const DELETE_HOUSE_BY_ID_FULFILLED =
  "mobilereality/HOUSES/DELETE_HOUSE_BY_ID_FULFILLED";
const DELETE_HOUSE_BY_ID_REJECTED =
  "mobilereality/HOUSES/DELETE_HOUSE_BY_ID_REJECTED";
const CLEAR_DETAILS = "mobilereality/HOUSES/CLEAR_DETAILS";
const FILTER_HOUSE_BY_ID = "mobilereality/HOUSES/FILTER_HOUSE_BY_ID";

export default {
  FETCH_HOUSES_REQUESTED,
  FETCH_HOUSES_FULFILLED,
  FETCH_HOUSES_REJECTED,
  FETCH_HOUSE_BY_ID_REQUESTED,
  FETCH_HOUSE_BY_ID_FULFILLED,
  FETCH_HOUSE_BY_ID_REJECTED,
  DELETE_HOUSE_BY_ID_REQUESTED,
  DELETE_HOUSE_BY_ID_FULFILLED,
  DELETE_HOUSE_BY_ID_REJECTED,
  CLEAR_DETAILS,
  FILTER_HOUSE_BY_ID
};
